### ISSUE TITLE
No download-specific widgets on non-download pages

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#111]
Find a way to handle this. You can place widgets anywhere, opening the door for users to place widgets where they don't necessarily belong. Either adjust the content or add a notice on the widget itself.

**Comment by SDavisMedia** [comment]
@mindctrl @sumobi @cklosowski @pippinsplugins Need some feedback here.

Vendd has widgets that should only be used on single download pages. `issue/111` branch has my attempt at a solution. Here's what it does:

**Front-end**

* Returns early out of the widget class if it's being rendered on a non-download page.

**Back-end (widgets.php [and customizer])**

* Adds notices to Vendd widgets about where they can be used.
* Uses Vendd's admin.css file to control the display of that notice based on whether or not the widget is in the Download Sidebar.

![screen shot 2015-11-09 at 8 29 24 pm](https://cloud.githubusercontent.com/assets/2359131/11054400/9e05d7aa-8720-11e5-9b1d-68af25b0fb15.png)

Assuming this approach is a good one, the only thing I don't like is the face that the widgets placed in the wrong sidebar still get counted as widgets in the sidebar on the front-end. So based on the screenshot above, you're left with:

![2015-11-09 at 8 31 pm](https://cloud.githubusercontent.com/assets/2359131/11054423/e669d172-8720-11e5-800c-8af7381e5aa9.png)

I'm tempted to say it's the user's fault at that point. Thoughts?

**Comment by spencerfinnell** [comment]
The notice is a pretty cool idea. I really hate how WordPress doesn't group widgets by their intended widget area. Usually I put the Widget Area in the name of the widget, but that ends up with super long widget names that are usually cut off on small screens.

Might have to borrow this.

**Comment by mindctrl** [comment]
My initial thought is if it requires doing something like this, it's probably best to be options in the customizer and not a widget at all. But I'm not sure if you can tie into the customizer panel for that widget area so the options would feel connected with the rest of the sidebar.

**Comment by SDavisMedia** [comment]
@mindctrl We'd lose way too much flexibility doing anything other than widgets.

**Comment by mindctrl** [comment]
@SDavisMedia here's what I meant. If all the options in the widget are turned into customizer options, you lose nothing and you only present them in the manner they're intended to be used. I'm just not sure if there's a way to hook into the panel of a specific widget area.

**Comment by mindctrl** [comment]
Totally forgot about ordering of the features.

With no widgets, what do you think about centering the body content column instead of having it pushed over?

**Comment by SDavisMedia** [comment]
@mindctrl The sidebar itself needs to _think_ it has no widgets. With the current method, it still thinks it does. So that's why I was asking for help in Slack and for feedback here. Because if you all know of a way to tell the sidebar that its only widgets are invalid and there for should act as if it has no widgets, then the default widgets can show again and there's no need to shift the content.

**Comment by mindctrl** [comment]
brb need more :coffee: 

Sorry, I get what you're saying finally. 

> I'm tempted to say it's the user's fault at that point. Thoughts?

I'm with you here I think, and it's easy enough to tell someone to remove the widget from the sidebar it's not intended to be used in.

**Comment by SDavisMedia** [comment]
@spencerfinnell @mindctrl Sweet! Thanks, gents!

I'll wait for a little more feedback before merging. 1.1.4 should be done today.

**Comment by pippinsplugins** [comment]
Looking shortly.

**Comment by pippinsplugins** [comment]
I like the notice and just returning early.

**Comment by SDavisMedia** [comment]
@pippinsplugins :+1:

**Comment by cklosowski** [comment]
:+1: for the notice. With the available options for intervention, I think it's the most plesant.

**Comment by SDavisMedia** [comment]
Woot!

**Comment by sumobi** [comment]
Late to the game, but :+1: for notice and what you have done. Can't think of a better way at this point in time (and I live in the future).

**Comment by SDavisMedia** [comment]
@sumobi haha good deal
