### ISSUE TITLE
Styles for <select> elements

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/vendd#112]
A customer asked about making the `<select>` dropdown menus on the checkout screen have a style that more closely matches the other elements. Something along the lines we do on the EDD site.

#### Vendd:
![image](https://cloud.githubusercontent.com/assets/1254870/9367687/fbcbd40e-468c-11e5-8558-3dd8259d2976.png)

#### EDD site:
![image](https://cloud.githubusercontent.com/assets/1254870/9367690/0864eaac-468d-11e5-93f7-2142234be155.png)

Any interest in this @SDavisMedia?

**Comment by SDavisMedia** [comment]
I don't know what I have against styling select elements. I never do for some reason. I'll add some styles.

**Comment by SDavisMedia** [comment]
I'm a goofball. I already added styles for select menus. Just not everywhere. Enhanced for checkout. :+1:
