### ISSUE TITLE
Refresh FES styles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#118]
Little things are changing all over the place in FES screwing with the styles. Do a thorough walkthrough. 

Gonna list stuff to fix as I see it:
- [x] http://glui.me/?i=enul6qg6qoo6gtu/2015-10-23_at_2.29_PM.png/

**Comment by pippinsplugins** [comment]
Most should be fixed in FES if appropriate.

**Comment by chriscct7** [comment]
Spencer did some fixes for invalid markup and added some new css classes.

**Comment by SDavisMedia** [comment]
It'll be Vendd adjustments. Most of it has to do with HTML and where/how it's being used. Not FES's fault. Just the nature of having to style for incorrect HTML and then it getting fixed. So it's a good thing.

**Comment by pippinsplugins** [comment]
Ah good deal

**Comment by SDavisMedia** [comment]
Gonna list stuff to fix as I see it:
* http://glui.me/?i=enul6qg6qoo6gtu/2015-10-23_at_2.29_PM.png/

**Comment by pippinsplugins** [comment]
Audio Player field needs a couple of small tweaks: https://cloudup.com/cpP-XQGK4iT

**Comment by SDavisMedia** [comment]
:+1:

**Comment by SDavisMedia** [comment]
that'll do it for now
