### ISSUE TITLE
research and account for WP title changes

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#119]
https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/

**Comment by SDavisMedia** [comment]
@tnorthcutt Woot! Thank you much! Perfect timing.

I think we should also add the check to ensure back compat. EDD requires WP 3.9.2 or higher while title tag support starts at WP 4.1. So it's probably best to include that.

```if ( ! function_exists( '_wp_render_title_tag' ) ) {
	function vendd_render_title() {
		?>
		<title><?php wp_title( '|', true, 'right' ); ?></title>
		<?php
	}
	add_action( 'wp_head', 'vendd_render_title' );
}
```

See any issues there? If not, you can add it to your PR and I'll get this in 1.1.4! Thanks again!

**Comment by SDavisMedia** [comment]
@tnorthcutt Also, with the function and title tag support in place, can you resubmit it branch `issue/119` instead?

**Comment by tnorthcutt** [comment]
@SDavisMedia 
![cool-dog-in-swing-sunglasses](https://cloud.githubusercontent.com/assets/796639/11078700/398f6036-87cd-11e5-9508-70e315bc7664.gif)

**Comment by SDavisMedia** [comment]
@tnorthcutt Woot woot! Thank you, sir! Very much appreciated. :sunglasses:
