### ISSUE TITLE
FES products tab using deprecated EDD_FES()->vendors->get_product_constant_name()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/vendd#120]
The `EDD_FES()->vendors->get_product_constant_name()` function is deprecated in FES 2.3. It should be updated soon after 2.3 is released.

See https://github.com/chriscct7/edd-fes/issues/849

**Comment by SDavisMedia** [comment]
Just now catching this somehow. :+1:

**Comment by SDavisMedia** [comment]
oops... mistake in that commit
