### ISSUE TITLE
site title anchor logic not working for empty carts

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#121]
`false === edd_get_cart_contents()` doesn't seem to work anymore. Needs `false == edd_get_cart_contents()` now for some reason.

**Comment by mindctrl** [comment]
This: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3893

**Comment by SDavisMedia** [comment]
@mindctrl Oh good call. I should actually just use `empty( edd_get_cart_contents() )`. Sweet. :+1:

**Comment by pippinsplugins** [comment]
@SDavisMedia `empty( edd_get_cart_contents() )` will generate a fatal error on some sites. Use"

```php
$cart = edd_get_cart_contents();
empty( $cart )
```

**Comment by SDavisMedia** [comment]
@pippinsplugins Got it!
