### ISSUE TITLE
main menu loads slow

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#138]
When the page loads, the main menu items load a bit slower. This is probably because of CSS transitions being too general. Let's tighten that up.

**Comment by SDavisMedia** [comment]
Relevant ticket: https://secure.helpscout.net/conversation/141376777/21818/

**Comment by SDavisMedia** [comment]
@mindctrl @cklosowski @spencerfinnell y'all got any clue why the main menu loads a bit slower? There's a slight delay. I thought maybe it was because of the background transitions so I made some adjustments. While that helps, I can see now that it's not the problem.

Something causes the menu to delay some CSS properties a bit as it displays. The links show up but the the menu (the `ul`) padding [I believe] delays as well as the menu item backgrounds. Whyyyyyyyy. :)

**Comment by spencerfinnell** [comment]
It happens no matter how many menu items there are?

**Comment by SDavisMedia** [comment]
@spencerfinnell Yup. I tried with my really short menu and no drop downs. Same behavior and I have no idea why.

**Comment by mindctrl** [comment]
@SDavisMedia you talking about the slight delay and shift that happens when the menu items load?

**Comment by SDavisMedia** [comment]
@mindctrl Yup. Even when I remove some CSS properties to view the behavior with barebones links, it still lags. The Font Awesome carets are not the culprit either. :flushed:

**Comment by mindctrl** [comment]
There's a transition on the padding around line 499 that appears to be causing part of it.

**Comment by SDavisMedia** [comment]
@mindctrl Already adjusted that in `issue/138`. https://github.com/easydigitaldownloads/vendd/commit/cf7a194753dde49ac30ec3c6f1216c8f980787bd

Or are you seeing a different one? (note: looks like I need to go through and get more specific with all of the transitions anyway)

**Comment by mindctrl** [comment]
@SDavisMedia that's the one I meant. I missed that commit.

**Comment by SDavisMedia** [comment]
@mindctrl No worries! I'm gonna keep looking for it. I just wondering if you guys had ever seen this before.

**Comment by SDavisMedia** [comment]
Gonna push this to 1.1.6. Need more time to figure it out. So weird.

**Comment by SDavisMedia** [comment]
I'm dropping this one. I'm pretty confident it is not a CSS issue. May have something to do with WordPress itself. Won't fix here.

**Comment by SDavisMedia** [comment]
Boooooom, thank you @mindctrl. 

This is happening because Underscores (what Vendd is based on) adds a class of `nav-menu` to the `ul` element identified as the menu that is to be hidden and toggled with the responsive menu behavior (all happens in the JS). I believe Underscores adds this class just to guarantee it will be there for its own purpose, considering things would not work as expected if it was removed.

Because this class is added through JS, loading that JS was delaying the CSS that uses the class... causing the menu to appear to "load slowly." So the solution is to hardcode the class on the menu element so JS no longer has to add it to guarantee its presence. We control Vendd so we can do that with no issues.
