### ISSUE TITLE
Should Vendd be enqueueing child themes' stylesheets?

### ISSUE THREAD

**Issue by tnorthcutt** [easydigitaldownloads/vendd#140]
I realized that in a child theme I'm building, I was inadvertently loading my `childtheme/style.css` twice, since Vendd is already doing that here: https://github.com/easydigitaldownloads/vendd/blob/release/1.1.4/functions.php#L129

Is it "best practices" (¯\_(ツ)_/¯) for a parent theme to use `get_stylesheet_uri()` like that, which results in loading the child theme's stylesheet if it exists, but not loading the parent theme's stylesheet (if the child theme exists)?

In my case, for now I'm not enqueueing the child theme's stylesheet, but I am enqueueing Vendd's stylesheet, since I want the vast majority of it to apply.

Maybe that's bad practice, and I should instead copy Vendd's styles to my child theme, and be loading only one stylesheet?

**Comment by spencerfinnell** [comment]
I don't think using the child theme CSS only is a good idea for that reason exactly. You shouldn't need to copy the whole file to your child theme. 

I like this method: https://github.com/Astoundify/marketify-child?files=1

Avoids using @import too which is ill advised as wel. You end up with two http requests but seems to be the most flexible.

**Comment by SDavisMedia** [comment]
@tnorthcutt Yup, I've actually been meaning to switch over to the method @spencerfinnell pointed out. I actually do it that way in some of my non-EDD themes. @mindctrl wants it that way too.

I think what I was wanting to do is prevent people from having to deal with a functions.php file at all if it wasn't necessary. But I'm not sure that holds enough weight.

I'll change this up in the next version.

**Comment by tnorthcutt** [comment]
@SDavisMedia One thing to consider: if you change this up, and child themes have been depending on the parent theme to load the child CSS, won't the update mean the child theme CSS no longer gets loaded?

Obviously this can be fixed with one line in a child theme's `functions.php`, but in the meantime it'll break, right?

**Comment by SDavisMedia** [comment]
@tnorthcutt Maybe I'm missing something but I don't see any reason why this should affect Vendd as a parent theme at all. Correct me if I'm wrong, but all that needs to happen is that people need to no longer `@import` the stylesheet from their child themes and just add the following to their child theme functions files:

```php
function vendd_enqueue_styles() {
	wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
}
add_action( 'wp_enqueue_scripts', 'vendd_enqueue_styles' );
```

I can't see anything breaking with the following scenarios:

1. The user changes nothing in his or her child theme. Everything should still work.
2. The user removes the import from his or her child theme stylesheet and adds the above code to the child theme functions file. Everything should be perfect.
3. The user **does not** remove the import from his or her child theme stylesheet and adds the above code to the child theme functions file. The parent stylesheet would be loaded. Then after _after_ that, the child theme stylesheet would be loaded with the same styles (thanks to the import) and then the custom styles below it.

Am I trippin' here or is this a change that I need to simply suggest to people (mainly from the hardcoded portion of the admin page where I say how to create a child theme)? `get_stylesheet_uri()` in Vendd should be fine as long as there is either an @import in the child theme, the above code in the child theme, or both. Right?

**Comment by SDavisMedia** [comment]
@mindctrl You mind reading this entire issue and letting me know what you think about my last reply? The goal is to make the necessary changes for best practices but also make sure no current sites are affected.

**Comment by tnorthcutt** [comment]
@SDavisMedia Reading over this again, I think where this will break is if people aren't using an `@import` in their child theme to load the parent (Vendd) stylesheet, but are instead enqueuing it – which is what I've done, since that's the "WordPress way".

So, I think there is potential for breakage if a child theme has been doing what I've been doing. But maybe I'm the only one doing that :wink:.

**Comment by SDavisMedia** [comment]
@tnorthcutt The thing is, though, nothing we do here can break anyone's child theme as long as I don't change the use of `get_stylesheet_uri()`. Using that is fine whether a child theme @imports or enqueues. They just have to do one of them. No existing child themes would be affected at all because the parent theme is not actually changing here.

I'm not sure what you did to load the same stylesheet twice but yea I think there was something unique going on here.

See my last commit or checkout branch `release/1.1.7` and navigate to the Vendd License page (with the parent theme activated) to see the new instructions I'm about to push out.

**Comment by SDavisMedia** [comment]
Okay this is good to go. New instructions included in the theme itself.
