### ISSUE TITLE
Vendor template notice

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#142]
`Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/localhost/edd/wp-content/plugins/edd-fes/classes/frontend/class-vendor-shop.php on line 141`

Only when no vendor is specified.

**Comment by SDavisMedia** [comment]
@chriscct7 I think this is because of FES, actually. Can you confirm before I close it out and open an FES issue?

**Comment by chriscct7** [comment]
This should be an FES issue

**Comment by chriscct7** [comment]
https://github.com/chriscct7/edd-fes/issues/934

**Comment by SDavisMedia** [comment]
@chriscct7 thanks
