### ISSUE TITLE
Add social media links to information bar

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#143]
It'd be great if there was a way to add Social Media profiles to the Information bar. Not sure that dashicons has all these, so we might need a custom Font Awesome set. Some I'd like to see:

Twitter
Facebook
Instagram
GitHub
Pinterest
Dribble

**Comment by SDavisMedia** [comment]
Vendd already has Font Awesome built in so that would work.

**Comment by SDavisMedia** [comment]
@cklosowski Checkout branch `release/1.1.5` and let me know what you think about what I added here. Fields are in the customizer in their own section.

![screen shot 2015-12-12 at 6 30 17 pm](https://cloud.githubusercontent.com/assets/2359131/11765174/1ef27a90-a101-11e5-80ef-c7e21bdf42e6.png)

They only output in the Information Bar at the moment but I have it set up to where they can easily be output anywhere else in the future with `vendd_social_profiles` hook.

**Comment by cklosowski** [comment]
:heart: This is exactly what I was thinking.

**Comment by cklosowski** [comment]
As mentioned in slack, I think the only thing I'd change is the font size. They look a little small.

**Comment by SDavisMedia** [comment]
Much better!

![screen shot 2015-12-12 at 8 10 37 pm](https://cloud.githubusercontent.com/assets/2359131/11765439/6f24212a-a10c-11e5-9749-3288680e5873.png)
