### ISSUE TITLE
Add hooks before and after the navigation items

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#144]
I was looking to add an item (programmatically) to the information bar menu area but there aren't any hooks in this. I think i'd be great to add something like:
```
<?php if ( has_nav_menu( 'info_bar' ) ) : ?>
	<div id="info-bar-navigation" class="secondary-navigation" role="navigation">
		<?php do_action( 'vendd_before_info_bar_menu' ); ?>
		<?php
			wp_nav_menu( array(
				'theme_location'	=> 'info_bar',
				'menu_class'		=> 'info-bar-navigation',
				'fallback_cb'		=> '__return_false',
				'depth'				=> -1,
			) );
		?>
		<?php do_action( 'vendd_after_info_bar_menu' ); ?>
	</div><!-- #info-bar-navigation -->
<?php endif; ?>
```

**Comment by spencerfinnell** [comment]
Can also filter `wp_nav_menu_items` which will allow you to append/prepend inside the actual menu structure if you're trying to add more links to the menu.

**Comment by cklosowski** [comment]
@spencerfinnell That's a possibility, but I was looking at just adding some informational items, not necessarily menu items. I'll try that too.

**Comment by cklosowski** [comment]
I was hoping to be able to do it without having to assign a menu.

**Comment by SDavisMedia** [comment]
Can't hurt anything. I tend to stay away from hooks in simple themes and promote the use of child themes. But considering it's such a busy and important template, I think hooks are a good idea.

**Comment by cklosowski** [comment]
I'll play around with both implementations and see what works better.

**Comment by spencerfinnell** [comment]
There is also `wp_nav_menu` which is all of the HTML of the menu, which would allow you to add stuff before/after on the outside of the menu (only if a location has been assigned).

**Comment by SDavisMedia** [comment]
Sorry, my comment is way out of place. Responding from my phone. I'm all for hacking the actual menu but like you said, Chris, I assumed you weren't actually just adding to the menu structure.

**Comment by cklosowski** [comment]
Closing this actually. @spencerfinnell has the right method there...
