### ISSUE TITLE
Prevent iOS devices from zooming on input focus

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#145]
Without the following CSS, iOS devices will 'zoom' in on the input fields when focused by tap, which makes the page slightly scroll to the side, or requires a pinch zoom out in order to get back to the right screen ratio:

```
@media screen and (-webkit-min-device-pixel-ratio:0) { 
  select,
  textarea,
  input {
    font-size: 16px;
  }
}
```

**Comment by SDavisMedia** [comment]
Yeeeeeeeeeeeeees.

**Comment by SDavisMedia** [comment]
@cklosowski I'm finding conflicting information about this. I think this method might be deprecated: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#-moz-device-pixel-ratio

I'm seeing this instead: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#resolution

I can't get either method to make a difference on my iPhone, though. What are you experiencing when you put your the in place?

**Comment by cklosowski** [comment]
@SDavisMedia Without this in place, and I click into a checkout field, it zooms in a bit, so that I can pinch-zoom back out. where as with this fix in place, clicking into a text field does not change my zoom of the page.

**Comment by SDavisMedia** [comment]
@cklosowski Yes that's how it works, I just couldn't get it to work. Didn't seem to make a difference for some reason. Unfortunately, I couldn't get your code or the other code I found to work. Trying multiple browsers, clearing caches, etc. No clue what's going on.

I'll dig deeper into it for 1.1.6.

**Comment by spencerfinnell** [comment]
Interested to see what you find on this. Would be nice to know. Everything I'm reading says the `16px` should fix it though.

**Comment by SDavisMedia** [comment]
Yea I'll give it a shot again and let you guys know.
