### ISSUE TITLE
add default download image capability

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#151]
Right now, you either upload a custom download image for each download or you have no download image. It would be nice if you could also choose one image as a default.

This shouldn't simply display by default. If the user does not upload a download image and wants to use the default, he or she should _choose_ to do that.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by SDavisMedia** [comment]
Fun. EDD's Customizer setting now has an image uploader and corresponding setting for whether or not the default product image is used (global). If uploaded and used, a default product image will show in all places where the standard Download (Featured) Image would have been.
