### ISSUE TITLE
Vendd Dies if EDD is deactivated

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#153]
If you disabled EDD, Vendd dies hard with a fatal error:
`[15-Jan-2016 01:43:04 UTC] PHP Fatal error:  Call to undefined function edd_get_cart_contents() in /Users/cklosowski/Development/demos/edd/wp-content/themes/vendd/header.php on line 48`

I know that Vendd shouldn't really be used without EDD, but we shouldn't give a fatal error when it's deactivated, for debugging and what not.

**Comment by cklosowski** [comment]
![screen shot 2016-01-14 at 6 45 03 pm](https://cloud.githubusercontent.com/assets/1390124/12343204/f0ee7ef2-baee-11e5-9b68-07c302a04222.png)

**Comment by mindctrl** [comment]
Think this is already fixed here: https://github.com/easydigitaldownloads/vendd/issues/149

**Comment by SDavisMedia** [comment]
Closing this as it's a duplicate. I'm about to update Vendd now. Sorry I didn't do this sooner.
