### ISSUE TITLE
Style recurring term notices from Recurring Payments 2.4

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/vendd#155]
Recurring Payments 2.4 is adding a display option for signup fees and recurring terms on purchase buttons. These need to be styled:

![screen shot 2016-01-28 at 3 31 04 pm](https://cloud.githubusercontent.com/assets/1034109/12659394/29778396-c5d4-11e5-80a0-1c2aa4164a37.png)
![screen shot 2016-01-28 at 3 31 16 pm](https://cloud.githubusercontent.com/assets/1034109/12659397/2f6589c4-c5d4-11e5-8510-89821bc08bb3.png)

These both get wrapped with a class of `eddr-notice`.

**Comment by pippinsplugins** [comment]
The `Added to Cart` text overlaps:
![screen shot 2016-01-28 at 3 32 37 pm](https://cloud.githubusercontent.com/assets/1034109/12659440/67bbb9e2-c5d4-11e5-8467-8e9ad5d1e19f.png)

**Comment by SDavisMedia** [comment]
Got it. :+1:

**Comment by SDavisMedia** [comment]
Starting with the single download sidebar... styled for both the widget and the default output with all RC scenarios considered:

![rc-download](https://cloud.githubusercontent.com/assets/2359131/13271629/181f2190-da4b-11e5-98d0-d396fd750c66.png)

More to follow.

**Comment by pippinsplugins** [comment]
That looks great.

**Comment by SDavisMedia** [comment]
All [downloads] shortcode scenarios are good - with or without Variable Pricing... multi-option or single-option purchase mode... with or without Item Quantities... with or without Variable Pricing Descriptions. Few examples:

![asdf](https://cloud.githubusercontent.com/assets/2359131/13272687/c6e4a3ba-da52-11e5-8ca3-1c5b395d297b.png)

More to follow.

**Comment by pippinsplugins** [comment]
Wonderful.

**Comment by SDavisMedia** [comment]
All aforementioned scenarios also good with the single download sidebar buttons. Forgot to mention/show that.

**Comment by SDavisMedia** [comment]
All scenarios good for just a regular purchase link int the content :persevere: : 

![screen shot 2016-02-23 at 6 14 19 pm](https://cloud.githubusercontent.com/assets/2359131/13273580/5e93ced8-da59-11e5-8946-2510f6a62a6e.png)
