### ISSUE TITLE
Difficulty in converting currency

### ISSUE THREAD

**Issue by msmaxsoft** [easydigitaldownloads/vendd#157]
Hello
Thank you very beautifully designed templates
I have a small problem with this template site (vendd)
I am from Iran and currency of my country (official) IRR (public) Toman!
All the products I units is Toman
And Toman units on all sites are properly displayed with the following code
----------------
/*
* START OF SECTION CONVERT
* How to convert rials to Tomans in easy digital downloads and remove the slash from the prices of products
*/

 
if ( ! function_exists( 'edd_toman_currency' ) ) {
	 
function edd_toman_currency( $formatted, $currency, $price ) {
			
	 if ( ! is_admin() ) {
							 
		$price = @str_replace( ',', '', $price );
							 
		$price = @$price / 10;

		$price = number_format( $price, 0, '', ',' );
	
		return $price . ' تومان';

	}
			
 	return $price . ' ریال';
	 }

}

add_filter( 'edd_rial_currency_filter_after', 'edd_toman_currency', 10, 3 );

add_filter( 'edd_rial_currency_filter_before', 'edd_toman_currency', 10, 3 );
	

/* END OF SECTION CONVERT*/
----------------
But when I add a product to your shopping cart
IRR  recorded the single currency in the basket! Just like the screenshot below.
https://drive.google.com/file/d/0Bz_nnfFwAbtzNFM5VXBCZWtZeGc/view?usp=sharing
and
https://drive.google.com/file/d/0Bz_nnfFwAbtzUnVVSm94TmtTTEk/view?usp=sharing
tank you

**Comment by pippinsplugins** [comment]
@msmaxsoft Please open a support ticket: https://easydigitaldownloads.com/support

Github is for development tracking and discussion only.
