### ISSUE TITLE
make sure child themes can host language files

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#163]

**Comment by SDavisMedia** [comment]
No changes needed, actually. Everything should be done from the child theme using `load_child_theme_textdomain()`. https://codex.wordpress.org/Function_Reference/load_child_theme_textdomain

This needs to have a doc. Gonna leave this open until I write it.

**Comment by SDavisMedia** [comment]
Done. http://docs.easydigitaldownloads.com/article/1228-how-do-i-translate-my-child-theme

**Comment by spencerfinnell** [comment]
> Unlike plugin language files, a name like my_child_theme-de_DE.mo will NOT work. Although plugin language files allow you to specify the text-domain in the filename, this will NOT work with themes and child themes. Language files for themes should include the language shortcut ONLY.

From what I can tell on that codex file the translation files need to be places in the child theme's directory so they can use the simplified language-only name.

**Comment by SDavisMedia** [comment]
@spencerfinnell I saw that in the Codex. I tried so many times to use `load_child_theme_textdomain()` hooked into `after_theme_setup` in the child theme and then have file names like `es_ES.mo` in the languages directory of the child and I just couldn't get it to work. 

Using `load_child_theme_textdomain()` is my first choice over using `wp-content/languages/themes` but I just couldn't get it to work in testing. Have you had luck using it?

**Comment by spencerfinnell** [comment]
Yep. 

```
function marketify_child_translation() {
	load_child_theme_textdomain( 'marketify', get_stylesheet_directory() . '/languages' );
}
add_action( 'after_setup_theme', 'marketify_child_translation' );
```

With the files in `/wp-content/themes/marketify-child/en_US.mo` and `/wp-content/themes/marketify-child/en_US.po`

**Comment by SDavisMedia** [comment]
@spencerfinnell Hmmm... did that several times (thought I did, I guess), and it wouldn't work.

Why are your files working from `/wp-content/themes/marketify-child/en_US.mo` and `/wp-content/themes/marketify-child/en_US.po`? Your `load_child_theme_textdomain()` references the `/languages` folder of the child theme, not the root.

**Comment by spencerfinnell** [comment]
Sorry, that was my mistake copying after testing that location. Was confirming both locations work (when the path is correct) and they did.

**Comment by spencerfinnell** [comment]
You're changing your WordPress install's language right? Or just test with en_US as well.

**Comment by SDavisMedia** [comment]
@spencerfinnell My bad I meant to say it's working for me now. I think I just tested so many different scenarios that I never actually tested the complete correct scenario. It's working, though. About to update the new doc. Thanks!

**Comment by spencerfinnell** [comment]
Great! I think the title should be more along "How to translate a theme via a child theme" or similar. You aren't really translating the child theme.

**Comment by SDavisMedia** [comment]
@spencerfinnell Good call. All updated. Thanks for the extra eyes! I definitely wanted to use this method over WP core files.

http://docs.easydigitaldownloads.com/article/1228-how-do-i-translate-my-theme-from-child-theme
