### ISSUE TITLE
prepare to move to wordpress.org

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#168]
Looks like we're going to move Vendd to wordpress.org. 

At a minimum, we'll need to remove the updater. Also will need to go over the theme standards and make sure I'm not doing anything illegal... Ex: having a WP core feature being turned off by default behind a Vendd option.

**Comment by cklosowski** [comment]
After some discussions with @SDavisMedia, moving to .org posses some real concerns on the functionality and ability to move quickly when it comes to version changes and bug fixes. For now we'll close this and continue to distribute on our own site.

Having this issue open for over 2 years with no real urge to move to .org yet, I don't see the immediacy to do this.
