### ISSUE TITLE
Demo: Vendor Dashboard images are broken

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/vendd#171]
https://easydigitaldownloads.com/vendd/fes-vendor-dashboard/

![image](https://cloud.githubusercontent.com/assets/282234/14409288/4464769c-ff17-11e5-83e0-b0d9d02c8a7b.png)

**Comment by mindctrl** [comment]
@slaFFik thanks for reporting this. @SDavisMedia I edited the page and changed the URLs to https, which is what's causing the problem, but the responsive images feature in WP is causing the srcset images to load over http. Not sure what the fix there is without just forcing all URLs to https.

**Comment by SDavisMedia** [comment]
@mindctrl Maybe disabling responsive images? https://gist.github.com/SDavisMedia/13f4c173c18855c60c4b

**Comment by mindctrl** [comment]
@SDavisMedia yeah that works too. We could edit the site in the Network Admin and change the URL to https. I'm betting that would fix the srcset URLs. Either is good with me though.

**Comment by SDavisMedia** [comment]
@mindctrl I don't follow how we'd do that in network admin but if you know, I say go for it.

**Comment by SDavisMedia** [comment]
That fixed it! Thanks for letting us know, @slaFFik.
