### ISSUE TITLE
Theme request a license key

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/vendd#172]
I guess it would be a mistake or unremoved old code

**Comment by chriscct7** [comment]
Licenses are required for this theme in order to get automatic updates for it. Free licenses are available via our website

**Comment by rubengc** [comment]
But you are preparing the theme to move to wordpress.org so will be extrange request a license when will get updated via wordpress

**Comment by chriscct7** [comment]
If we move forward with that it will be handled as part of #168 as it's
just a matter of removing the licensing line.

**Comment by SDavisMedia** [comment]
Correct. The updater will be removed when issue 168 is handled.
