### ISSUE TITLE
shortcode-price.php should use edd_get_lowest_price_option instead of edd_price

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#184]
Line affected:
https://github.com/easydigitaldownloads/vendd/blob/master/edd_templates/shortcode-content-price.php#L2

This line uses `edd_price` to return a price for a download, but when variable pricing is enabled, it returns the default price, and if one is not set, it uses the lowest price. We should instead be using `edd_get_lowest_price_option` here for the variable pricing logic.
![screen shot 2016-09-22 at 9 41 49 am](https://cloud.githubusercontent.com/assets/1390124/18767947/ec1064aa-80d6-11e6-9d8a-b367ba978e25.png)

![screen shot 2016-09-22 at 9 41 42 am](https://cloud.githubusercontent.com/assets/1390124/18767949/ef9b9748-80d6-11e6-90c8-53bda9a74fba.png)

**Comment by SDavisMedia** [comment]
Oh nice catch!

**Comment by SDavisMedia** [comment]
That was definitely an oversight. Looking good now. Thanks!

**Comment by cklosowski** [comment]
Np @SDavisMedia found it b/c of a Themeforest theme doing the same thing :)
