### ISSUE TITLE
Add admin instructions for activating license

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#190]
Just to make it easier since it's a two step process. 

<img width="866" alt="screenshot 2016-10-23 10 25 28" src="https://cloud.githubusercontent.com/assets/2359131/19628096/0c023f9e-990b-11e6-8806-5c8537e352d2.png">

Take notes from Volatyl (minus the yellow).

<img width="742" alt="screenshot 2016-10-23 10 22 07" src="https://cloud.githubusercontent.com/assets/2359131/19628069/99572004-990a-11e6-9ade-6f474839664b.png">

**Comment by SDavisMedia** [comment]
P.S. Remove that extra period while you're in there. https://cl.ly/470H0t061d3B

**Comment by pippinsplugins** [comment]
👍

**Comment by SDavisMedia** [comment]
<img width="748" alt="screenshot 2017-02-12 13 50 20" src="https://cloud.githubusercontent.com/assets/2359131/22866364/3760a7d0-f12a-11e6-8005-372d4af9f401.png">
