### ISSUE TITLE
Add VENDD_VERSION to the CSS enqueue as well

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#192]
We're adding the VEND_VERSION to the script enqueuing but not to our style enqueueing:
https://github.com/easydigitaldownloads/vendd/blob/master/functions.php#L134

We should add the version there too so that when changes are pushed out that affect the CSS< the version is appended and caches are busted.

**Comment by SDavisMedia** [comment]
@cklosowski Why do I feel like I've done this in Vendd a bunch of times already? Lol I must be going crazy.

Yes definitely, I'll get it in here and check other themes as well. :+1:
