### ISSUE TITLE
Add setting to remove featured image from product page

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#193]
We have it for posts and pages. Should be there for downloads as well.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
<img width="1230" alt="screenshot 2017-02-12 12 43 50" src="https://cloud.githubusercontent.com/assets/2359131/22865859/ea8f895c-f120-11e6-9ee5-5868a9ca8f62.png">

**Comment by pippinsplugins** [comment]
👍
