### ISSUE TITLE
Add styles for All Access

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/vendd#198]
The All Access extension has an option to output some additions to the normal Purchase Form. To help tighten it up a little bit I would like to add the following styles to the style.css file for Vendd:

```
/*--------------------------------------------------------------
>>> All Access
>>> https://easydigitaldownloads.com/downloads/all-access/
--------------------------------------------------------------*/
#edd-aa-login-modal-content #edd_login_form{
	margin-top:0px;
}
.edd-aa-login-purchase-normal-plus-aa-mode{
	margin-top:20px;
}
.edd-aa-buy-instructions{
	display:block;
	margin-bottom:5px;
}
.edd-aa-login-wrapper{
	margin-top:5px;
}
```

Before styles added:
<img width="438" alt="screen shot 2017-03-01 at 12 15 44 am" src="https://cloud.githubusercontent.com/assets/1638128/23446969/8cd60f28-fe15-11e6-8176-40d26c572e8c.png">

After styles added:
<img width="418" alt="screen shot 2017-03-01 at 12 19 59 am" src="https://cloud.githubusercontent.com/assets/1638128/23446973/97a277ac-fe15-11e6-8ca5-3c512d0d1212.png">

**Comment by SDavisMedia** [comment]
@mintplugins how does everything look on the [downloads] shortcode? Please check that out as well and make sure it's good to go in that tighter space.

**Comment by mintplugins** [comment]
@SDavisMedia Should the purchase form normally be showing on the downloads shortcode? Even with buy_button set to "yes" it isn't showing for me - even with All Access deactivated.

**Comment by mintplugins** [comment]
My bad - I never clicked on the "plus" button before :P

It looks good here!
<img width="291" alt="screen shot 2017-03-03 at 10 23 08 am" src="https://cloud.githubusercontent.com/assets/1638128/23556695/79d6346a-fffb-11e6-8692-4fc0b42de46c.png">

**Comment by SDavisMedia** [comment]
Looks like this got added to AA core. :+1:
