### ISSUE TITLE
Show Categories/Tags on Downloads grid separation

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#204]
Rather than having a single option, it would be useful to have two separate options for categories and tags alike. Since in most cases tags can be overwhelming for sites with lots of products.

**Comment by SDavisMedia** [comment]
@davidsherlock Great idea! I agree.

**Comment by SDavisMedia** [comment]
@davidsherlock mind checking out branch `issue/204` and testing this? It should split the setting into two separate settings and their values should match what you were displaying previously (so initially, both cats and tags will show if you had the old setting checked, and they will not show if you didn't).

**Comment by SDavisMedia** [comment]
Working well on my end as well as Pippin's. If you do test, David, and run into issues, just let me know!

**Comment by davidsherlock** [comment]
Works perfect @SDavisMedia! Will let you know if I experience any issues while developing/testing.

I want to suggest one more feature however (somewhat related), outwith editing the template files via a child theme, it's not possible to set the number of columns for the taxonomy/search results pages within the customizer. Maybe a general option could be added that applied to all these pages for column count?

**Comment by davidsherlock** [comment]
@SDavisMedia, not to be a pain but you couldn't by any chance squeeze #203 into the next point release?

**Comment by SDavisMedia** [comment]
@davidsherlock please do me a favor and try to comment either on the relevant issues or open new issues for new requests.
