### ISSUE TITLE
FES vendor contact form improvement

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#206]
At the minute the FES contact form is inserted at the bottom of the vendor which is somewhat confusing to the users, I propose that the contact form be a button under the author bio with "Message Vendor" text and when clicked a pop-up modal box containing the contact form would show.

**Comment by SDavisMedia** [comment]
@davidsherlock I'm not a huge fan of modals as a base standard in a free, basic theme. I feel like they're "extra" considering how heavily they depend on JS and some users have issues on mobile, JS conflicts, etc. I'd rather leave this one to child theme devs, or even better, those creating their own parent themes (even if it's a Vendd fork).
