### ISSUE TITLE
Page Builder template

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#207]
It would be useful to have a page builder template with no guttering (padding or margins) to facilitate the various lightweight page builders like Beaver Builder, Elemenator, etc.

**Comment by SDavisMedia** [comment]
@davidsherlock I'm definitely not in favor of this one. I don't want to promote the use of page builders at all. The template can be created straight from a child theme if needed.

**Comment by davidsherlock** [comment]
No worries @SDavisMedia, I'll include it in my child theme. As a side note, I'm also against page builders.

**Comment by SDavisMedia** [comment]
@davidsherlock Have you considered forking Vendd and making a parent theme? It's not necessary, of course, but I just want to make sure it's clear that we're not at all against that. We would love to have more people building themes for EDD.

**Comment by davidsherlock** [comment]
@SDavisMedia, i have but I feel a child theme is best because I would rather leave room for improvements at your side.

**Comment by SDavisMedia** [comment]
@davidsherlock okay good deal. I'm gonna go ahead and close this issue. I think I'm gonna work on two Vendd releases to come out soon. Either two or one... I might just combine everything on my short list and jump to release 1.2. We've got a Stripe update as well as an FES update coming out that will both require theme updates for styling. So changes coming very soon.

**Comment by davidsherlock** [comment]
@SDavisMedia, I'm actually considering forking the Vendd theme and building a commercial theme around it - Is this okay with you? I will of course change the name, licensing, etc.

**Comment by pippinsplugins** [comment]
Vendd is distributed under GPL so yep, that's perfectly fine :) We only ask that you include attribution inside of your theme.

**Comment by davidsherlock** [comment]
@pippinsplugins, perfect - How do you like the attribution to be presented within the theme files? Is there a set standard?

Here are a few work in progress screenshots of the development so far :)

![screenshot 2017-05-22 15 35 37](https://cloud.githubusercontent.com/assets/22668877/26313953/5988e20a-3f04-11e7-8cab-fc03e1d3c130.png)

![screenshot 2017-05-22 15 35 00](https://cloud.githubusercontent.com/assets/22668877/26313959/602ad50a-3f04-11e7-811b-08c475e28744.png)

![screenshot 2017-05-22 15 34 18](https://cloud.githubusercontent.com/assets/22668877/26313977/6b0890fc-3f04-11e7-80a1-55b75f7fb202.png)

![screenshot 2017-05-22 15 34 07](https://cloud.githubusercontent.com/assets/22668877/26313987/6fe705a4-3f04-11e7-9b9c-0c5729764bca.png)

![screenshot 2017-05-22 15 38 29](https://cloud.githubusercontent.com/assets/22668877/26314079/b8e043c4-3f04-11e7-98fd-da80a7e7a93c.png)

Going to implementing better support for audio/video previewing, FacetWP filtering (with all elements styled for), more custom page templates (no page builder bloat though), lots of smaller improvements and a dark material design inspired colour scheme.

I will also build a few 'light' colour scheme child themes as well to cater for all audiences!

**Comment by SDavisMedia** [comment]
@davidsherlock that is looking _awesome_, man! Forking is the way to go if you intend to build a commercial theme. Doing so with a child theme just isn't a good idea, IMO. When it comes to updates for your users and where they'll place their customizations, it just becomes a nightmare.

Please place the attribution somewhere in the style.css top comment block. Lines 15 and 16 are an example of my attributions to Underscores in another theme of mine: https://github.com/SDavisMedia/enterprise-lite/blob/master/style.css

**Comment by davidsherlock** [comment]
@SDavisMedia, thanks man really appreciate it! :) Going to be make something really good for EDD, so all bases are covered in terms of real-world usability.

Will adhere to the attribution in the CSS files as mentioned!
