### ISSUE TITLE
Customizer callback sanitization missing

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#213]
I run the theme through a theme checker and it flagged up that some of the add_setting() functions within the customizer were missing sanitization callbacks. I haven't had a chance to drill into the actual code, but felt it was worth mentioning here for a future release and to make sure the theme passes all checks.

**Comment by SDavisMedia** [comment]
@davidsherlock It's mainly tripping over color options. There's a `sanitize_hex_color` sanitization function but is only available when the Customizer is actually loaded. So in order for it to be truly effective, it has to be used in the styles themselves. Vendd does this with its `vendd_sanitize_hex_color`  function [here](https://github.com/easydigitaldownloads/vendd/blob/master/inc/customizer.php#L772) and you can see it wrapping hex values [throughout the code](https://github.com/easydigitaldownloads/vendd/blob/master/inc/customizer.php#L804). Theme checker is going to trow flags if it's not on the `add_setting()` method, though, so I'll put it there too.

It's also tripping over my (custom) [arbitrary](https://github.com/easydigitaldownloads/vendd/blob/master/inc/customizer.php#L14) [HTML](https://github.com/easydigitaldownloads/vendd/blob/master/inc/customizer.php#L147) "setting" that I created just to add useful output where I want it. It's not a setting. It accepts no user input. A dummy sanitization callback should do the trick to shut Theme Checker up.

Lastly, the image upload settings may be flagged, though they shouldn't be. WordPress itself handles file type checking. So the sanitization is actually done and is not truly needed on the method. Pretty sure I can use `'sanitize_callback' => 'esc_url_raw'` to pass the Theme Checker, though.

In other words, one sec.

**Comment by SDavisMedia** [comment]
That'll do it. Took care of some other Theme Checker crap while I was in there. What's left is based on the fact that we control and distribute the theme. If it were to be hosted on wordpress.org, which is the standard used in the Theme Checker, things like git files and EDD's Software Licensing code wouldn't even been included... which clears the rest of the warnings. Merging into master now. :+1:

**Comment by davidsherlock** [comment]
Thanks @SDavisMedia, updated my code base with your commit. Passing all checks now!
