### ISSUE TITLE
Excerpt filtering

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#217]
Because I run a site that sells audio files, I noticed that when a WordPress audio player is the first element in the content and no excerpt is set manually, the archive pages pull the audio player into the archive page downloads, messing up the layout. I recommend we filter the excerpt from any media before being output and reduce page load time.

**Comment by pippinsplugins** [comment]
Does WordPress itself remove media from excerpts? In other words, is this a Vendd specific behavior or a WordPress behavior?

**Comment by davidsherlock** [comment]
I believe it's default WordPress behaviour but designed more so for blog post excerpts where more space is available (and it makes sense). In the case of Vendd, it results in a strange layout due to the size of the product boxes.

Regardless, I can take care of this in my own theme. Just giving a heads up mainly.

**Comment by SDavisMedia** [comment]
Thanks. Definitely WordPress, though. Someone could easily optimize a different audio player that works/looks fine in such a cramped space. So I'd rather not filter anything out by default. I've actually seen one site with an itty bitty audio player running on downloads in Vendd. 

Closing, but keep the suggestions coming. :+1:
