### ISSUE TITLE
Allow social network icons on vendor profile page

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#219]
On the vendor profile page I feel it would be a good idea to show the social icons/networks of the vendor, here is an example of how I did it on my theme.

![screenshot 2017-05-26 11 54 01](https://cloud.githubusercontent.com/assets/22668877/26492062/38514b28-420a-11e7-9c22-1cfcc1302c48.png)

**Comment by SDavisMedia** [comment]
@davidsherlock I _swear_ I built this already. I just know I did... how you have it displayed is exactly how I did it. Or maybe that's how I imagined it. 🤔 Either way, yes.

**Comment by SDavisMedia** [comment]
<img width="1204" alt="screenshot 2017-05-27 02 26 00" src="https://cloud.githubusercontent.com/assets/2359131/26520284/38f0a6b2-4284-11e7-8a5c-c124f3433d6b.png">

**Comment by davidsherlock** [comment]
Great minds think alike @SDavisMedia! :) Working well here.

One quick question for you, do you know if it's possible to add additional social networks to the additions Jetpack includes? I can't find any examples anywhere...I want to add Instagram and SoundCloud.

**Comment by SDavisMedia** [comment]
@davidsherlock I don't unfortunately. I haven't played with that at all yet. Sorry!
