### ISSUE TITLE
FES Vendor page title improvement

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#220]
I noticed the vendor page/profile title is set as the store or display name, which is great but I feel it should be prefixed with the site name the same as the EDDcategories/tags.

**Comment by SDavisMedia** [comment]
@davidsherlock I don't think that would hurt anything but I also don't think it's a needed change. Any particular reason why you'd want to see that there?

My fear is that the site name could drown out the store name in some cases:

**Wonderful WordPress Plugin Marketplace: xCode**
xCode Bio

I don't see the need to run that risk and possibly drown out vendor store specific output with the site name when it's already known and displayed right above in the header.

**Comment by spencerfinnell** [comment]
I agree it's not needed by default. Pretty sure FES used to do "The Store of $username" by default which was also too long.

**Comment by davidsherlock** [comment]
@SDavisMedia, it was mainly for congruency with the marketplace. So people knew the "seller" (or author) was a member of the site in question.

Here is a screenshot of how Envato do it:

![screenshot 2017-05-27 00 57 56](https://cloud.githubusercontent.com/assets/22668877/26515931/97fe8014-4277-11e7-9569-f343a8cf8b3d.png)

Regardless, I agree with you both here and like how it works as is.

**Comment by davidsherlock** [comment]
Here is Creative Market and Etsy:

![screenshot 2017-05-27 00 59 55](https://cloud.githubusercontent.com/assets/22668877/26515966/fc660e6e-4277-11e7-87d9-6e7fee7c1835.png)

![screenshot 2017-05-27 01 00 39](https://cloud.githubusercontent.com/assets/22668877/26515973/09b94aae-4278-11e7-8dd4-3dce35bc13bc.png)

**Comment by spencerfinnell** [comment]
*documwnt* title would be great. wp_title() vs the_title()

**Comment by SDavisMedia** [comment]
@spencerfinnell definitely... could just filter `document_title_parts`

**Comment by SDavisMedia** [comment]
FES already filters the doc title on this page, actually. Gotta use `pre_get_document_title` instead.
 
<img width="392" alt="screenshot 2017-05-28 09 25 04" src="https://cloud.githubusercontent.com/assets/2359131/26530310/942a8b84-4387-11e7-8d5f-3ac12f480080.png">

@davidsherlock @spencerfinnell Thoughts?

**Comment by SDavisMedia** [comment]
"Sean Davis Store" is my vendor store name, by the way. It's what FES was already using. The logic simply appends "on {site name}" to whatever document title already exists.
