### ISSUE TITLE
Purchase button/options focus improvement when scrolling

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#229]
It goes without saying that the focus of the Vendd theme is purchasing digital goods and services, however if you have a large product description the user can't impulsively purchase the item without scrolling to the top again.

I recommend a bar like this appears when scrolling a certain amount:

https://creativemarket.com/styledstocksociety/1527114-Hot-Pink-Green-Desktop-Bundle

https://www.designcuts.com/product/thicket-thatch-patterns/

Ideally this would also function on mobile devices when scrolling, where the problem is made worse by the fact the button/options are far at the bottom.

**Comment by SDavisMedia** [comment]
@davidsherlock _maybe_ in the future, but I doubt. Again, expectation management is important. Vendd is free. It's a great on-boarding theme. I'm not trying to introduce brand new users to functionality that they will expect from everything installation of EDD, regardless of theme. How Vendd behaves should be close to how EDD behaves by default.

**Comment by davidsherlock** [comment]
Cool, thanks @SDavisMedia. I'll build all this stuff into my commercial theme forked from Vendd and see how it goes! Already got media support added to the frontend, so will add this as well.

**Comment by SDavisMedia** [comment]
Closing. Don't think this is something I'd ever put in Vendd since it's more of an on-boarding theme.
