### ISSUE TITLE
Call to undefined function vendd_edd_fes_author_url() in sidebar

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#252]
`Fatal error: Uncaught Error: Call to undefined function vendd_edd_fes_author_url() in vendd/sidebar-download.php:29`

**Comment by cklosowski** [comment]
So it's a weird scenario when this comes up...

I'm using a `Vendd Child` theme, and i have the following filter in there:
`add_filter( 'vendd_show_single_download_author_details', '__return_true' );`

But the block that is running this fatal error is wrapped in:
`<?php if ( vendd_fes_is_activated() || apply_filters( 'vendd_show_single_download_author_details', false, $post ) ) { ?>`

Meaning `if FES is active OR if the filter is true`, however the section does use FES specific functions, so it seems like this should be an `&&` but that would cause some logic issues for the current usage in that by default it would show the author details when FES is active, even if that filter returns `false`, or when the filter returns `true`.

**Comment by SDavisMedia** [comment]
@cklosowski I actually avoided this problem in another part of the sidebar. Looks like I just failed to catch them all.

That should fix it.

**Comment by cklosowski** [comment]
Works perfect @SDavisMedia kick up a PR and i'll merge it for you.
