### ISSUE TITLE
Compatibility with EDD 3.0 and CSS Grid 

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/vendd#256]
Vendd will need to be updated as per the "other notes" section on https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6852

> Vendd overrides widths based on the column class used. Because of the CSS specificity, it will override the width: auto rule added to reset the widths. All Vendd will need is to remove the widths and it's method of using display: inline-block. It can use CSS grid and floats will be provided as a fallback.

Note: this will need to be released for EDD 3.0, possibly at the same time. In my testing so far however, the proposed PR works fine with the current master branch of EDD so could be possibly released earlier. Might need some help testing this.

**Comment by amdrew** [comment]
Added initial WIP PR: https://github.com/easydigitaldownloads/vendd/pull/257

Tested with 3 pages. A normal page, a page with the "Full-width Page" page template and the "EDD Downloads" page template. On each page I've used the following:

```
[downloads columns="1"]
[downloads columns="2"]
[downloads columns="3"]
[downloads columns="4"]
[downloads columns="5"]
[downloads columns="6"]
```

Still need to test with IE to make sure the default EDD floats works correctly. IE 11 should use CSS grid.

**Comment by SDavisMedia** [comment]
Initial test looks pretty good. Responsive behavior has been affected, though. At 1000px I have a media break that turns some download configurations into 2 columns. That's missing. I'll look into what additional tweaks are needed.

**Comment by SDavisMedia** [comment]
Working on getting this merged with full backwards compatibility (from 3.0). It's time to push out a Vendd update that can be used while testing EDD 3.0 stuff.

**Comment by SDavisMedia** [comment]
And that'll do it. So much testing. 😓 

The [downloads] shortcode is now fully supported for EDD 3.0 as well as previous versions. Only very slight visual differences between the two that no one will ever notice whether they update now or after EDD 3.0 is released. So this can go out now.
