### ISSUE TITLE
Warning on PHP 7.3

### ISSUE THREAD

**Issue by nutsandbolts** [easydigitaldownloads/vendd#263]
Customer report via https://secure.helpscout.net/conversation/820909922/104495?folderId=180499

When running PHP 7.3, the focus page and landing page templates display the following:

`Warning: count(): Parameter must be an array or an object that implements Countable in /public_html/wp-includes/post-template.php on line 293`

WP Core introduced `is_countable()` in 4.9.6: https://make.wordpress.org/core/2018/10/15/wordpress-and-php-7-3/

**Comment by SDavisMedia** [comment]
I don't believe this is a Vendd issue. There's an ongoing discussion over on EDD core. I'm going to let that play out first.

**Comment by nutsandbolts** [comment]
Agreed. Given the info that has come in over there, this is likely irrelevant for Vendd.
