### ISSUE TITLE
improve EDD check for when there are no download items

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#54]
I'm setting up Vendd's demo on an EDD multisite site and because it has EDD installed, EDD related features are showing, like the cart information display in the header.

Not only will the cart always be empty, right now it doesn't even link to anywhere because the checkout page hasn't been set in the EDD settings. I'd prefer that certain **front-end features** like that do not show if the system doesn't even have any download entries.

This is probably a super edge case but I think it can be improved.

**Comment by SDavisMedia** [comment]
After a chat with @mindctrl, he confirmed some thoughts I have about this one. We'll keep the header cart even when no downloads have been created.

**Comment by chriscct7** [comment]
I think you should put a filter to turn them off. For example, if someone has EDD active but they're using it as a catelog and thus have no add to cart buttons enabled, they probably don't want the header cart. Filters let them do whatever it is they want.

**Comment by chriscct7** [comment]
Reopening for consideration of ^

**Comment by SDavisMedia** [comment]
I like. :+1:
