### ISSUE TITLE
Filters for Download Details

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#58]
There are a number of items in the sidebar for the download details that would be beneficial to have some filters on.

This should be things like stats, versioning, etc.

**Comment by SDavisMedia** [comment]
I agree, @cklosowski.

Can you provide a **tested** `add_filter()` example for `vendd_show_sales_in_sidebar`? I'm having trouble getting it to work. Examples for the other two would be great too so I can toss them in a doc.

If we can get this in today in time for launch, I'd like to.

**Comment by cklosowski** [comment]
@SDavisMedia These should do the trick:
```
function test_vendd_show_sales_in_sidebar( $show_sales, $downlaod ) {
	// To test against a specific download us $download->ID
	return true;

}
add_filter( 'vendd_show_sales_in_sidebar', 'test_vendd_show_sales_in_sidebar', 10, 2 );

function test_vendd_is_licensed( $is_licensed, $download ) {
	// To test against a specific download us $download->ID
	return true;
}
add_filter( 'vendd_download_is_licensed', 'test_vendd_is_licensed', 10, 2 );

function test_vendd_version( $version, $download ) {
	// To test against a specific download us $download->ID
	return '1.1';
}
add_filter( 'vendd_download_version', 'test_vendd_version', 10, 2 );
```

**Comment by cklosowski** [comment]
Just added in another one for the sales count:
```
function test_vendd_sales_count( $count, $post ) {
	return 5;
}
add_filter( 'vendd_download_sales_count', 'test_vendd_sales_count', 10, 2 );
```

**Comment by SDavisMedia** [comment]
Everything is working great on my end. Merged. Thanks! :+1:
