### ISSUE TITLE
Improve Checkout or Amazon Payments

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/vendd#65]
With Amazon payments coming to EDD Core, we'll need to fix up the checkout to be more friendly with their widgets:
![image](https://cloud.githubusercontent.com/assets/1390124/8015160/21c27394-0b8b-11e5-8405-16c61e58c310.png)

**Comment by pippinsplugins** [comment]
Not sure how much of this is vendd specific. At the moment both vendd and
2015 have overlap issues

**Comment by cklosowski** [comment]
Agree. Just want to make sure test Vendd specifically since it's our flagship theme.

**Comment by pippinsplugins** [comment]
:+1: :)

**Comment by SDavisMedia** [comment]
Gonna see if anything needs to happen here as soon as Amazon finally decides to call or text me to verify my account set up. :unamused:

**Comment by SDavisMedia** [comment]
We're all good here.
