### ISSUE TITLE
Add a default search form

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#69]
I originally considered have a search form aligned to the right in the main menu area. http://glui.me/?i=rofu9m0sze8vduu/2015-06-07_at_1.56_PM.png/ Also considering having it in the Information Bar which would remove the need to handle issue #68.

@mindctrl @cklosowski thoughts?

**Comment by mindctrl** [comment]
I like your idea of not showing the info bar in #68. Just feels cleaner if people don't want it there.

When I originally set up Vendd, I added the search widget to the sidebar (http://cl.ly/image/3d393H450Q3U) and I think it looks good. But a search box in the menu area would be nice and make it more accessible since it would show up on pages that don't use the sidebar. I like the right aligned shot you're considering.

**Comment by cklosowski** [comment]
I like it there, could also just use an icon of the magnifying glass, and upon clicks opens up the search box so we're not using up the real-estate for poeple that aren't using it. Plus, form inputs are just generally ugly so if we can make them out of the way until needed that's better.

**Comment by SDavisMedia** [comment]
Yea that's what I'm planning. Main menu area it is.

**Comment by cklosowski** [comment]
There are a few things we could do here too. Make it an option to show/hide. Also. Possible to make it only search download post type?

Just throwing out ideas.

**Comment by SDavisMedia** [comment]
@cklosowski I'm definitely making it an option considering its placement can interfere with those who choose to have super long menus. 

As for only searching download post types, I've done that in Quota and Shoppette and ended up removing it. It caused more headaches than anything. I handed search results control back over to the user. I think it's best to leave it that way unless the search form is located in a template that is 100% specific to a post type... like if we ever add a search form to the downloads template or something.

**Comment by SDavisMedia** [comment]
@cklosowski @mindctrl I've got a concept on branch `issue/69`. Few notes: 

1. I'm having troubles with Safari that I haven't sorted out yet.
2. I wanted to align it right which is definitely possible and how I had it for a while, but I can't trust users to keep their menu widths short enough to respect it. Of course there are ways to avoid a collision between search and menu items, but I think this is a smarter approach.
3. I haven't added a Customizer option to toggle the search functionality yet. I'll do it once we decide on something.

![screen shot 2015-06-22 at 9 21 38 am](https://cloud.githubusercontent.com/assets/2359131/8283991/1edc67a6-18c0-11e5-88c6-c26ab1c95e62.png)

![screen shot 2015-06-22 at 9 22 38 am](https://cloud.githubusercontent.com/assets/2359131/8284023/48f27b34-18c0-11e5-9a76-8df3d9efbc02.png)

![screen shot 2015-06-22 at 9 22 10 am](https://cloud.githubusercontent.com/assets/2359131/8284004/30dc0984-18c0-11e5-9246-52cbd8a9d349.png)

**Comment by cklosowski** [comment]
I' getting a dark background on the search input in chrome...has this been updated since the screenshots above?

![screen shot 2015-06-22 at 7 36 00 pm](https://cloud.githubusercontent.com/assets/1390124/8297860/037cff4c-1916-11e5-880b-04e261634803.png)

Other than that, if you can mimic in Safari then i think you're golden. like that. I agree about the length thing too...

**Comment by SDavisMedia** [comment]
The background is dark only on focus. Same color as the menu items otherwise. "Otherwise" includes when you're on a search results page. The form is expanded by default to show the search term. If you click it, though, it's in focus and the background is dark again. So the screenshots above are accurate. I just didn't show a focus state.

**Comment by cklosowski** [comment]
Ah ok :+1:

**Comment by SDavisMedia** [comment]
Alright this is good to go now. @mindctrl tracked down the Safari issue for me. The search form sits behind a new customizer setting that I'll leave unchecked by default. You can find the setting in the Navigation section of the customizer. All good for the next release.
