### ISSUE TITLE
Add filters for FES-only front-end output

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#72]
Nothing wrong with adding filters so the following output can display even when FES is not activated. We talked about this, @mindctrl. Just gonna add a filter and have the stuff off by default.

![2015-06-15 at 10 41 am](https://cloud.githubusercontent.com/assets/2359131/8163871/47783156-134b-11e5-8495-ed733e8afe9b.png)

![2015-06-15 at 10 42 am](https://cloud.githubusercontent.com/assets/2359131/8163873/4e264b96-134b-11e5-98c9-17f6bf3601f0.png)

**Comment by cklosowski** [comment]
YES!

**Comment by mindctrl** [comment]
Nice. Good idea.

**Comment by SDavisMedia** [comment]
@cklosowski Think you can have a look at the new filters for me? They're in branch `issue/72`. If you approve, they're going in 1.1.1. Notes & filters for easy testing (FES deactivated):

**Downloads Shortcode Author/Byline:**

I didn't break this one down by download... it's all or nothing. I think that's the right decision but I'm open to feedback.

```php
add_filter( 'vendd_show_downloads_byline', '__return_true' );
```

=====

There's a filter for the entire section and filters for all the output... all of which can be global or by post ID: 

**Single Download Author Details (entire section false by default):**
```php
// global
add_filter( 'vendd_show_single_download_author_details', '__return_true' );

// by post ID
function test_vendd_show_single_download_author_details( $show_author_details, $post ) {
	if ( $post->ID == 148 ) {
		$show_author_details = true;
	}
	return $show_author_details;
}
add_filter( 'vendd_show_single_download_author_details', 'test_vendd_show_single_download_author_details', 10, 2 );
```

**Single Download Author Avatar (true by default):**
```php
// global
add_filter( 'vendd_show_single_download_author_avatar', '__return_false' );

// by post ID
function test_vendd_show_single_download_author_avatar( $show_author_avatar, $post ) {
	if ( $post->ID == 148 ) {
		$show_author_avatar = false;
	}
	return $show_author_avatar;
}
add_filter( 'vendd_show_single_download_author_avatar', 'test_vendd_show_single_download_author_avatar', 10, 2 );
```

**Single Download Author Name (true by default):**
```php
add_filter( 'vendd_show_single_download_author_name', '__return_false' );

function test_vendd_show_single_download_author_name( $show_author_name, $post ) {
	if ( $post->ID == 148 ) {
		$show_author_name = false;
	}
	return $show_author_name;
}
add_filter( 'vendd_show_single_download_author_name', 'test_vendd_show_single_download_author_name', 10, 2 );
```

**Single Download Author Since (true by default):**

```php
add_filter( 'vendd_show_single_download_author_since', '__return_false' );

function test_vendd_show_single_download_author_since( $show_author_since, $post ) {
	if ( $post->ID == 148 ) {
		$show_author_since = false;
	}
	return $show_author_since;
}
add_filter( 'vendd_show_single_download_author_since', 'test_vendd_show_single_download_author_since', 10, 2 );
```

**Single Download Author Links (true by default):**

```php
add_filter( 'vendd_show_single_download_author_links', '__return_false' );

function test_vendd_show_single_download_author_links( $show_author_links, $post ) {
	if ( $post->ID == 148 ) {
		$show_author_links = false;
	}
	return $show_author_links;
}
add_filter( 'vendd_show_single_download_author_links', 'test_vendd_show_single_download_author_links', 10, 2 );
```

**Comment by SDavisMedia** [comment]
Also note that when you elect to show the author byline in the downloads shortcode and FES is deactivated, there's no author archive to link to at the moment. That's going to be tricky. For now, it's just the text, no link.

**Comment by cklosowski** [comment]
@SDavisMedia Looks good, I'll test them out Monday morning. Love this idea.

**Comment by SDavisMedia** [comment]
Sweeeet. Thanks!

**Comment by cklosowski** [comment]
These look great.
