### ISSUE TITLE
Author names should link to author pages

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/vendd#80]
This: http://screencloud.net/v/9rpe  should link to the author page (there's a function in FES for this) if FES is active. Also maybe a "see more products by {vendorname}" at the bottom of the product page

**Comment by SDavisMedia** [comment]
Added. :+1: Turns into just text if FES is deactivated and [the filter](https://gist.github.com/SDavisMedia/aa873dcc063be82903fe#file-gistfile1-php) is used to show author info.

![2015-06-30 at 1 55 pm](https://cloud.githubusercontent.com/assets/2359131/8439163/bea70a14-1f2f-11e5-8adc-b079df5c2f59.png)
