### ISSUE TITLE
Go all out on search results!

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#82]
So instead of letting search results show all post types the same like I do in every other theme, or leaving it up to users to do some search filtering on their own, I want to build a single search template that showcases all post type results in one view. The page will section things off logically, of course. Yup. It's gonna be pretty awesome.

**Comment by SDavisMedia** [comment]
Boom. New setting in the Content Settings to activate Advanced Search Results. The template will show downloads just like the rest of the site and split the post and page results in a nice way. Love it.

![screen shot 2015-07-06 at 1 57 41 am](https://cloud.githubusercontent.com/assets/2359131/8517109/8a390c80-2382-11e5-9ba2-f105f0ed88e5.png)

**Comment by spencerfinnell** [comment]
Fancy.

FYI `echo ucfirst( $last_type ) . ' ' . __( 'Results:', 'vendd' );` is not translatable.

Should be:

`printf( __( '%s Results:', 'vendd' ), ucfirst( $last_type ) );`

Also I think most people don't put the `:` in, but not sure what the actual rule is.

**Comment by SDavisMedia** [comment]
@spencerfinnell Fancy indeed. :nail_care:

I didn't want the post type name to be translatable but that was probably a bad idea. People should definitely have full control over that title. I'll adjust it. 

I typically don't want the `:` in there but I was thinking about users editing the string. Put it in the translation-ready string and they can easily adjust it with "Say What?". Put it outside of the string and they can only remove it by overriding the template. Thoughts?

**Comment by spencerfinnell** [comment]
Agreed, which is why I usually include it as well.

You could use `_x()` and make a note that the `%s` should remain and not be replaced (and that it will be automatically changed to the post type label). But really it's not a huge deal in my opinion if they do it. Just make sure any included translations don't.

**Comment by SDavisMedia** [comment]
We're right on the same page. About to push this now:

`printf( _x( '%s Results:', 'post search results title', 'vendd' ), ucfirst( $last_type ) );`
`printf( _x( '%s Results:', 'page search results title', 'vendd' ), ucfirst( $last_type ) );`

**Comment by SDavisMedia** [comment]
Dropped the `:` altogether. :+1: https://github.com/easydigitaldownloads/vendd/blob/release/1.1.2/content/content-advanced-search.php#L30

Thanks a ton for the feedback!
