### ISSUE TITLE
Widgets to replace default sidebar display

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#83]
Vendd has a pretty nice default sidebar for download pages. But if you add a widget to the sidebar, you're stuck having full control of the content. So there should be usable widget for every widget-like section that displays in the sidebar by default. 

If the widget doesn't already exist, I guess it's time to add widgets to the theme.

**Comment by mindctrl** [comment]
What do you think about always showing the purchase button by just moving it above the dynamic_sidebar check? It's a critical feature and would always make that part of the display consistent. Then deal with the other issues in widgets or whatever.

**Comment by SDavisMedia** [comment]
I feel like I shouldn't have to force that on people. The Download Details widget does the same thing for them. I figure I either give them a default sidebar or they take full control of it (which is why I have to build those other widgets). Honestly, the purchase button is only critical at the top of the sidebar if the user wants it to be.

**Comment by mindctrl** [comment]
That's legit. I didn't mean the position was critical, just the feature. But using the widget instead is a great option for full control. While testing that, I found a bug in the Download Details widget I need to report in EDD.
