### ISSUE TITLE
Improve RTL styles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#89]
I see at least one little thing that could be improved: http://glui.me/?i=6l2f6jsdij69vpf/2015-07-07_at_9.33_AM.png/ That's enough for a full look at it again. Nothing was needed initially.

**Comment by SDavisMedia** [comment]
Also: http://glui.me/?i=frsv10d6t1ihja1/2015-07-07_at_9.36_AM.png/

**Comment by zahedfathi** [comment]
Thanks for your attention
I will complete the rtl.css

**Comment by zahedfathi** [comment]
But my problem no solved
I disabled all plugins but still some icons from fontawesome not shown

**Comment by SDavisMedia** [comment]
Hi, Zahed. Please respond to the email I sent you so we can troubleshoot from the support ticket. This would not be the appropriate support channel.

**Comment by spencerfinnell** [comment]
If you ever want to add build tools you could use https://github.com/cssjanus/grunt-cssjanus which is what core does and takes care of 90%+ for you. We've had fairly good results with it. With some adjustments to your LTR CSS you can get most of it converting right over.

**Comment by SDavisMedia** [comment]
@spencerfinnell Nice! I'm going to look into it for sure.
